export async function createSpotifyPlaylist(
  accessToken: string,
  userId: string,
  playlistName: string,
  trackIds: string[]
) {
  const createResponse = await fetch(
    `https://api.spotify.com/v1/users/${userId}/playlists`,
    {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Content-Type": "application/json" 
      },
      body: JSON.stringify({
        name: playlistName,
        description: "Generated by Playfull.",
        public: false,
      }),
    }
  );

  if (!createResponse.ok) {
    throw new Error("Failed to create playlist.");
  }

  const playlist = await createResponse.json();

  const trackUris = trackIds.map(id => `spotify:track:${id}`);

  for (let i = 0; i < trackUris.length; i += 100) {
    const batch = trackUris.slice(i, i + 100);

    await fetch(
      `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
      {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ uris: batch }),
      }
    );
  }

  return {
    playlistId: playlist.id,
    playlistUrl: playlist.external_urls.spotify,
    trackCount: trackIds.length,
  };
}
